### ISSUE TITLE
Cannot update plugins

### ISSUE THREAD

**Issue by IvoPereira** [evertramos/docker-wordpress-letsencrypt#18]
Hello,

For every plugin I am trying to update, I get a message like:

> An error occurred while updating Akismet Anti-Spam: Could not create directory.

This is of course related to folder permissions, but I've just followed the instructions in the README.md. Shouldn't it be aware of those issues and handle it all alone?

Anyone facing the same issue?

**Comment by evertramos** [comment]
Hello @IvoPereira,

I was on vacation reason why it took a couple days to reply.

The first time you run this container, you probably will not have this issue, because it will create the folders for you automatically, but if you already created the folders where you want to host your files you might will have to change 'wp-content' folder's group to 'www-data' and set permissions to 775.

Here is an example, just in case:

```bash
$ chgrp -R www-data /path/to/your/files/wp-content
$ chmod 775 -R /path/to/your/files/wp-content
```

Don't forget to specify at the end the wp-content so all files will be 775 which you might not want it this way.

Please advise if it did the trick.

**Comment by pathros** [comment]
I arrived here because of the same problem. Exploring my folders, I realized that the script set the permissions to some `33:tape` ... except for the `wp-content/` folder. That was set to _root_. I am using CentOS and what I just did was to type in the terminal:

```$ sudo chown -R 33:tape wp-content/```

And that did the trick.

So, maybe does the owner name vary somehow? Because `www-data` does not exist anywhere on the system.
