### ISSUE TITLE
How do you backup your wordpress installs?

### ISSUE THREAD

**Issue by markusila** [evertramos/docker-wordpress-letsencrypt#39]
@evertramos  In some recent issues i've read that you "back up your install by command line",
do you have some script you could share?

**Comment by evertramos** [comment]
Hello @markusila!

It´s been a while I don´t check and update this repo... but I am working since a few month in new whole environment to wordpress sites but for now I am using this:

https://github.com/evertramos/docker-wordpress-backup

I plan to release some new code soon I will update all my repos with some info when its done.
